# Nylo - Micro-framework for Flutter.
#
# ! IMPORTANT !
# Run: 'flutter pub run nylo_framework:main project:init'
#
# This creates an .env file for you at the project.
# You need a .env file for the project to build.
#
# ! DOCS !
# https://nylo.dev
# Author: Anthony Gordon <agordon@nylo.dev>

name: Klinsy
description: Recurring Tasks Manager

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+5

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  url_launcher: ^6.0.9
  google_fonts: ^2.1.0
  analyzer: ^1.6.0
  adaptive_theme: ^2.2.0
  intl: ^0.17.0
  page_transition: ^2.0.2
  nylo_framework: ^1.1.0
  nylo_support: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  yaml: ^3.1.0
  path: ^1.8.0
  uuid: ^3.0.4
  sqflite: ^2.0.0+3
  camera: ^0.9.2+1
  path_provider: ^2.0.2

dev_dependencies:
  build_runner: ^2.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.4

# APP ICON
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "public/assets/app_icon/icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/assets/fonts/
    - public/assets/images/nylo_logo.png
    - public/assets/images/no-photo.png
    - lang/en.json
    - lang/de.json
    - .env
    - pubspec.yaml
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#   fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
